In [564]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [2581]:
import numpy as np
import numpy.ma
import matplotlib
import matplotlib.pyplot as plt
from anytime_logistic import *

# Synthetic Experiment for Logistic Regression
**Generate synthetic data**

In [2826]:
p = np.array([1,1]) ## cache hit rate 
n = 2000
d = 2
X_train, y_train = generate_synthetic_data(n,d,p)
X_test_o, y_test = generate_synthetic_data(n,d,p)

In [2828]:
X_test = modify_data(X_test_o,X_train,p)

In [2829]:
X_train_mod = modify_data(X_train,X_train,p)

In [2820]:
np.mean(X_test[:,1]==y_test)

0.39350000000000002

In [2821]:
X_test0 = modify_data(X_test,X_train,p,'zero')

In [2822]:
lam = np.logspace(-3,3,7)
lam

array([  1.00000000e-03,   1.00000000e-02,   1.00000000e-01,
         1.00000000e+00,   1.00000000e+01,   1.00000000e+02,
         1.00000000e+03])

**Anytime Logistic Regression**

In [2799]:
acc_alr_list=[]
for i in lam:
    print 'lam: ', i
    model = anytime_logistic(i)
    model.fit(X_train,y_train,p,'anytime')
    print 'anytime lr --theta: ', model.theta
    y_pred_alr = model.predict(X_test)
    acc_alr = np.mean(y_pred_alr==y_test)
    print 'accuracy for anytime lr: ', acc_alr
    acc_alr_list.append(acc_alr)

lam:  0.001
coef
[[  9.18904240e+01   0.00000000e+00]
 [  0.00000000e+00   1.10951919e-02]]
anytime lr --theta:  [ 0.00812779 -0.39280865]
accuracy for anytime lr:  0.3425
lam:  0.01
coef
[[  9.18994240e+01   0.00000000e+00]
 [  0.00000000e+00   2.00951919e-02]]
anytime lr --theta:  [ 0.00813694 -0.3724512 ]
accuracy for anytime lr:  0.3225
lam:  0.1
coef
[[ 91.989424     0.        ]
 [  0.           0.11009519]]
anytime lr --theta:  [ 0.00818997 -0.24915574]
accuracy for anytime lr:  0.3555
lam:  1.0
coef
[[ 92.889424     0.        ]
 [  0.           1.01009519]]
anytime lr --theta:  [ 0.00820596 -0.05893571]
accuracy for anytime lr:  0.345
lam:  10.0
coef
[[ 101.889424      0.        ]
 [   0.           10.01009519]]
anytime lr --theta:  [ 0.00750763 -0.00547977]
accuracy for anytime lr:  0.3375
lam:  100.0
coef
[[ 191.889424      0.        ]
 [   0.          100.01009519]]
anytime lr --theta:  [ 0.00401091 -0.00202287]
accuracy for anytime lr:  0.33
lam:  1000.0
coef
[[ 1091.889424 

**Vanilla Logistic Regressin**

In [2830]:
X_test_o

array([[ 1,  1],
       [ 1, -1],
       [ 1, -1],
       ..., 
       [ 1, -1],
       [-1,  1],
       [-1,  1]])

In [2831]:
acc_vlr_list=[]
lam = [0.001]
for i in lam:
    print 'lam: ', i
    clf = anytime_logistic(i)
    clf.fit(X_train,y_train,p,'vanilla')
    print 'vanilla lr --theta: ', clf.theta
    y_pred_vlr = clf.predict(X_test_o)
    acc_vlr = np.mean(y_pred_vlr==y_test)
    print 'accuracy for vanilla lr: ', acc_vlr
    acc_vlr_list.append(acc_vlr)

lam:  0.001
coef
[[ 0.001  0.   ]
 [ 0.     0.001]]
vanilla lr --theta:  [ 3.96505782 -0.4665404 ]
accuracy for vanilla lr:  0.6405


**sampling method**

In [2801]:
acc_samp_list = []
for i in lam:
    print 'lam: ', i
    samp = anytime_logistic(i)
    samp.fit(X_train_mod,y_train,p,'sampling')
    print 'sampling --theta: ', samp.theta
    y_pred_samp = samp.predict(X_test)
    acc_samp=np.mean(y_pred_samp == y_test)
    print 'accuracy for sampling method: ', acc_samp
    acc_samp_list.append(acc_samp)

lam:  0.001
coef
[[ 0.001  0.   ]
 [ 0.     0.001]]
sampling --theta:  [ 0.02006425 -0.42506752]
accuracy for sampling method:  0.413
lam:  0.01
coef
[[ 0.01  0.  ]
 [ 0.    0.01]]
sampling --theta:  [ 0.01862382 -0.40231898]
accuracy for sampling method:  0.335
lam:  0.1
coef
[[ 0.1  0. ]
 [ 0.   0.1]]
sampling --theta:  [ 0.01081215 -0.2617264 ]
accuracy for sampling method:  0.331
lam:  1.0
coef
[[ 1.  0.]
 [ 0.  1.]]
sampling --theta:  [ 0.00211924 -0.05931259]
accuracy for sampling method:  0.3225
lam:  10.0
coef
[[ 10.   0.]
 [  0.  10.]]
sampling --theta:  [ 0.00028656 -0.0082926 ]
accuracy for sampling method:  0.332
lam:  100.0
coef
[[ 100.    0.]
 [   0.  100.]]
sampling --theta:  [  6.99881005e-05  -2.02997549e-03]
accuracy for sampling method:  0.3245
lam:  1000.0
coef
[[ 1000.     0.]
 [    0.  1000.]]
sampling --theta:  [  33.48338759 -974.44753777]
accuracy for sampling method:  0.412


# QS learning

In [2497]:
data,target = make_classification(n_samples=10000, n_features=4)
data = preprocessing.scale(data)
X = np.array(data[0:n/2,:])
y = np.array(target[0:n/2])
X_test = np.array(data[n/2:,:])
y_test = np.array(target[n/2:])

In [2498]:
clf = anytime_logistic(1)
clf.fit(X,y,p,'clf')
clf.theta

array([ 0.09524455,  0.16580545,  0.00371149,  0.13731159])

In [2501]:
p = np.array([0.8,0.1,0.9,0.2])
p

array([ 0.8,  0.1,  0.9,  0.2])

In [2502]:
X_test = modify_data(X_test,p)
X_test

array([[ 0.        ,  0.        , -0.92999819,  0.        ],
       [-1.27474732,  0.        ,  1.09056918,  0.        ],
       [ 0.38991638,  0.        , -0.96223211,  0.        ],
       ..., 
       [-1.11457557,  0.        ,  0.        ,  0.        ],
       [ 0.41782101,  0.        , -0.20060765,  0.        ],
       [ 0.60714799,  0.        , -0.48151875,  0.        ]])

In [2503]:
X_mod = modify_data(X,p)
X_mod

array([[ 0.92050246,  0.        , -0.65402055,  0.        ],
       [-1.39852604,  0.        ,  0.97868298,  0.        ],
       [-0.69961217,  0.        , -0.36537809,  0.        ],
       ..., 
       [-1.69913164,  0.        ,  1.79120399,  0.        ],
       [ 0.        ,  0.        ,  1.7853146 ,  0.        ],
       [-0.99714073,  0.        ,  1.90961834,  0.        ]])

In [2460]:
def check_zero(x):
    if 0 not in x:
        return -1
    else:
        List = []
        for i in range(len(x)):
            if x[i] == 0:
                List.append(i)
        return tuple(List)

In [2461]:
def remove_feature(X,key):
    XX = np.array(X)
    if key==-1:
        return XX
    else:
        XX = np.delete(XX,key,1)
        return XX

In [2504]:
dic = {}
y_pred = []
for i in range(X_test.shape[0]):
    key = check_zero(X_test[i,:])
    if key in dic:
        model = dic[key]
        pred = model.predict(X_test[i,:])
        y_pred.append(pred)
    else:
        model = anytime_logistic(1)
        XX = remove_feature(X,key)
        pp = np.ones((XX.shape[1],))
        model.fit(X,y,pp,'clf')
        pred = model.predict(X_test[i,:])
        y_pred.append(pred)
        dic[key] = model
y_pred = np.array(y_pred)
np.mean(y_pred==y_test)

0.72747368421052627

In [2505]:
anytime = anytime_logistic(1)
anytime.fit(X,y,p,'anytime')
y_pred = anytime.predict(X_test)
np.mean(y_pred == y_test)

coef
[[  1.25323782   0.           0.           0.        ]
 [  0.          10.23858352   0.           0.        ]
 [  0.           0.           1.11845109   0.        ]
 [  0.           0.           0.           5.34020009]]


0.7241052631578947

In [2506]:
anytime.theta

array([ 0.03503724,  0.03347463,  0.00149004,  0.03795098])

In [2510]:
clf = anytime_logistic(1)
clf.fit(X,y,p,'clf')
y_pred_clf = clf.predict(X_test)
np.mean(y_pred_clf==y_test) 

0.72747368421052627

In [2511]:
clf.theta

array([ 0.09524455,  0.16580545,  0.00371149,  0.13731159])

In [2512]:
clff = anytime_logistic(1)
clff.fit(X_mod,y,p,'clf')
y_pred_clf = clff.predict(X_test)
np.mean(y_pred_clf==y_test) 

0.70821052631578951

In [2515]:
N,d=X.shape

In [2518]:
M = X.sum(axis=0)

In [2536]:
M[0] = 0
M

array([  0.        ,  36.90207796,  -0.3985337 ,  29.7757945 ])

In [2542]:
yy = (M>0).astype('int32')
yy 

array([0, 1, 0, 1], dtype=int32)

In [2544]:
yyy = (M>=0).astype('int32')
yyy

array([1, 1, 0, 1], dtype=int32)

In [2545]:
y = (yy+yyy)/2.0

array([ 0.5,  1. ,  0. ,  1. ])

In [2577]:
y=(np.random.rand(10)+0.5).astype('int32').reshape(10,1)

In [2578]:
x = np.tile(y,(1,2))

In [2579]:
x

array([[0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0]], dtype=int32)